name: Greetings

on: [pull_request_target, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
      - uses: actions/first-interaction@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          issue-message: "Thank you for your valuable input, @${{ github.actor }}! 🎉 We appreciate you bringing up this issue and contributing to the progress of this project!"
          pr-message: "Great job on making your first pull request, @${{ github.actor }}! 🎉 Congrats! Wishing you all the best on your open-source journey ahead!"
